### ISSUE TITLE
Unable to login I get error invalid login 

### ISSUE THREAD

**Issue by breechiteri** [ruddell/ignite-jhipster#29]
I am not able to login to my Frontend the backend is running ok and I have copied the URL to AppConfig.js. On my android virtual device I also get a warning : NetInfos change event is deprecated. Listen to the connection Change event instead.
NetInfo.fetch is deprecated. Use NetInfo.getConnecyionInfo() instead. Where should I configure this changes?

**Comment by ruddell** [comment]
The NetInfo warnings are unrelated and can be ignored.  

Here's what I did to start and connect:
 - Start JHipster backend with `mvn`
```
----------------------------------------------------------
	Application 'jhipster' is running! Access URLs:
	Local: 		http://localhost:8080
	External: 	http://192.168.58.1:8080
	Profile(s): 	[swagger, dev]
----------------------------------------------------------
```
 - Copy the external API url from your JHipster Backend output into `apiUrl` in AppConfig.js
 - Start Ignite JHipster frontend with `react-native run-android`
 - Log in works through the specified IP.  Localhost doesn't work on an Android emulator/device because it refers to the device instead of your computer.

Check in your android browser if you can connect to the apiUrl.

**Comment by breechiteri** [comment]
Thank you i followed your instructions and it has worked
