### ISSUE TITLE
Could not login/register account on real device

### ISSUE THREAD

**Issue by xuuz** [ruddell/ignite-jhipster#36]
Dear @ruddell 
Many thanks for your great work, just one problem I face now, when I run the app on simulator both iOS and Android are ok, but when run on real device, in can not connect to API, I have expose APi on hosting as well then replace:
<code>
  apiUrl: 'https://demodomain.xyz/',
  appUrlScheme: 'demoapp',

</code>
But it's not worked on real device, on simulator is  ok

Do I missing some configuration?

Thanks

**Comment by ruddell** [comment]
Are you able to access your backend (apiUrl) from iOS Safari or the Android Browser?  Try debugging your requests with either [Reactotron](https://github.com/infinitered/reactotron) (use [v1.1.5](https://github.com/infinitered/reactotron/releases/tag/v1.15.0)) which is preconfigured or the [React Debugging tools](https://facebook.github.io/react-native/docs/debugging.html#chrome-developer-tools)

**Comment by xuuz** [comment]
Thanks for your answer @ruddell ,
Currently when I debug I see the Status code return 0, but I try on postman, chrome,safari, login is ok
Just one more thing I using ignite to create app so that it's using depedency: "ignite-jhipster": "^1.9.0",

I'm using     "jhipsterVersion": "4.14.1",  with JWT token login.
Thanks

**Comment by ruddell** [comment]
If you are testing on Postman, that's not on the device.  The API URL has to be accessible to the real device, that's why I said test in your mobile browser (the one on the real device).  Status Code 0 means no response from the API so it seems to be unreachable.

I just tested on my iPhone and could log into the [sample app](https://github.com/ruddell/IgniteJhipsterSampleApp)'s API fine.  I'm guessing the Android version is working because you registered the other day ;P

When testing locally without a backend deployed, you can use your computer's local network IP (something like `10.0.0.145`, depends on your computer).

**Comment by xuuz** [comment]
Thanks for your support @ruddell , it's worked fine now, because the android version was too old, after upgrade every thing work well now, Thanks a million @ruddell
