### ISSUE TITLE
Entity generator doesn't handle LocalDate properly

### ISSUE THREAD

**Issue by mraible** [ruddell/ignite-jhipster#53]
I've generated an entity with the following JDL:

```
entity Points {
  date LocalDate required,
  exercise Integer,
  meals Integer,
  alcohol Integer,
  notes String maxlength(140)
}
```

There seem to be a couple issues with using this in Ignite JHipster:

1. When I create a new record, the date wants me to select a time as well as a date. All I want is a date selector, not time.
2. When I try to edit the record, I get an error: `TypeError: props.date.getTime is not a function`.

![image](https://user-images.githubusercontent.com/17892/46378534-2205e200-c659-11e8-9a56-2f27cab0853d.png)

Here's what the data looks like in the record I'm editing:

```
id:1051
date:2018-10-04
exercise:1
meals:1
alcohol:1
notes:Notes
user:null
```

**Comment by mraible** [comment]
I was able to solve the first issue (date picker render a date and a time) by specifying `mode: date` on the date field in `PointEntityEditScreen`. It still seems to recored a time, but at least the picker only shows a date.

```
  formOptions: {
    fields: {
      ...
      date: {
        mode: 'date',
        returnKeyType: 'next',
        onSubmitEditing: () => this.refs.form.getComponent('exercise').refs.input.focus()
      },
      ...
    }
  },
```

![image](https://user-images.githubusercontent.com/17892/46444219-0412ad00-c73f-11e8-8346-f75413a69086.png)

![image](https://user-images.githubusercontent.com/17892/46444232-1260c900-c73f-11e8-8f3c-bfd66f17d6dc.png)

Unfortunately, the 2nd issue still happens.

**Comment by ruddell** [comment]
So this was all happening because the form library expected a JS date but JHipster sends a string date.  I added some date transforms so when a single entity is fetched, the date is formatted as expected.  When it's displayed, it's also formatted back to the LocalDate (on the edit/detail screens).

With those fixes, LocalDate fields work as expected.  I also fixed the yellowbox error.  I didn't test Instant or ZonedDateTime but I plan on adding some E2E tests soon.
