### ISSUE TITLE
Unexpected keys error after generating a new app

### ISSUE THREAD

**Issue by mraible** [ruddell/ignite-jhipster#70]
**Describe the bug**

I tried to reproduce my [Build a Mobile App with React Native and Spring Boot](https://developer.okta.com/blog/2018/10/10/react-native-spring-boot-mobile-app) tutorial with the latest releases of JHipster and Ignite JHipster. When I launch the app in iOS Simulator, the following error occurs.

![screen shot 2019-01-28 at 8 51 55 am](https://user-images.githubusercontent.com/17892/51848082-2cb84700-22da-11e9-8bd0-4a9050d851b8.png)

**Instructions To reproduce**

https://github.com/oktadeveloper/okta-react-native-spring-boot-example/blob/demo-updates/demo.adoc

**JHipster app's `.yo-rc.json`**

```
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "es"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.okta.developer",
    "packageFolder": "com/okta/developer",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": ["protractor"],
    "websocket": false,
    "applicationType": "monolith",
    "baseName": "HealthPoints",
    "authenticationType": "oauth2",
    "buildTool": "gradle",
    "clientFramework": "react",
    "useSass": true,
    "jhipsterVersion": "5.8.0",
    "skipUserManagement": true,
    "clientPackageManager": "npm",
    "cacheProvider": "ehcache",
    "serverPort": "8080",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  },
  "entities": ["Points", "BloodPressure", "Weight", "Preferences"]
}
```

**Entity JDL or JSON files**

https://github.com/jhipster/jdl-samples/blob/master/21-points.jh

**Versions (please complete the following information):**
 - OS: macOS 10.14.2 (18C54)
 - Ignite JHipster Version: 2.0.3
 - Node Version: 11.6.0

**Comment by mraible** [comment]
After I ran `ignite generate import-jdl ../21-points.jh`, everything works. I'll try the steps again to confirm.

**Comment by ruddell** [comment]
This happens when an old Redux store is loaded that contains a key that is no longer present in the app.  On the initial generation, you have no entity keys in your reducer (but your previous state from the same app might).  There are two workarounds:
 - Increment your [`reducerVersion`](https://github.com/ruddell/IgniteJhipsterSampleApp/blob/5b72aee01a0d4ac56f3fb0beca22d335d270811e/App/Config/redux-persist.js#L7) in app/config/redux-persist.js which will resets the saved state
 - Add the keys to the [blacklist](https://github.com/ruddell/IgniteJhipsterSampleApp/blob/5b72aee01a0d4ac56f3fb0beca22d335d270811e/App/Config/redux-persist.js#L11), refresh, remove from the blacklist

There's currently an issue about this here, don't know if any progress has been made. https://github.com/rt2zz/redux-persist/issues/618

**Comment by mraible** [comment]
I tried the steps a second time (after erasing all contents and settings in Simulator) and now I get a new error.

<img width="545" alt="screen shot 2019-01-28 at 9 51 50 am" src="https://user-images.githubusercontent.com/17892/51852059-7d33a280-22e2-11e9-9198-bef6aaf49c62.png">

**Comment by ruddell** [comment]
I can't find a way to reproduce the issue, your config works fine on my end.  It also doesn't affect the E2E tests.  It looks like the image isn't being loaded?

**Comment by mraible** [comment]
Yeah, I tried a couple more times and couldn't reproduce it either. I'll close this issue.
