### ISSUE TITLE
ignite-jhipster could not generate social login

### ISSUE THREAD

**Issue by xuuz** [ruddell/ignite-jhipster#71]
**Describe the bug**
Hi @ruddell , I saw this boilerplate already supported good social login, but when I try today, it not generate social login, did you disable it or which version we should use? thanks again your help, and this is very interesting framework

**JHipster app's `.yo-rc.json`**

{
	"generator-jhipster": {
		"promptValues": {
			"packageName": "com.news.reader",
			"nativeLanguage": "en"
		},
		"jhipsterVersion": "4.14.3",
		"baseName": "ReaderWebApp",
		"packageName": "com.news.reader",
		"packageFolder": "com/news/reader",
		"serverPort": "8080",
		"authenticationType": "jwt",
		"cacheProvider": "no",
		"enableHibernateCache": false,
		"websocket": false,
		"databaseType": "mongodb",
		"devDatabaseType": "mongodb",
		"prodDatabaseType": "mongodb",
		"searchEngine": "elasticsearch",
		"messageBroker": false,
		"serviceDiscoveryType": false,
		"buildTool": "maven",
		"enableSocialSignIn": true,
		"enableSwaggerCodegen": false,
		"jwtSecretKey": "5a7f2e356d76324df094d07cd749f2dc75eb82b3",
		"clientFramework": "angular1",
		"useSass": false,
		"clientPackageManager": "yarn",
		"applicationType": "monolith",
		"testFrameworks": [
			"gatling",
			"cucumber",
			"protractor"
		],
		"jhiPrefix": "jhi",
		"enableTranslation": true,
		"nativeLanguage": "en",
		"languages": [
			"en",
			"ar-ly",
			"hy",
			"ca",
			"zh-cn",
			"zh-tw",
			"cs",
			"da",
			"nl",
			"et",
			"fa",
			"fr",
			"gl",
			"de",
			"el",
			"hi",
			"hu",
			"id",
			"it",
			"ja",
			"ko",
			"mr",
			"pl",
			"pt-br",
			"pt-pt",
			"ro",
			"ru",
			"sk",
			"sr",
			"es",
			"sv",
			"tr",
			"ta",
			"th",
			"ua",
			"vi"
		]
	}
}

**Entity JDL or JSON files**

**Versions (please complete the following information):**
 - OS:  Mac OS 10.14
 - Ignite JHipster Version: latest version (2.0.3 )
 - Node Version:v11.2.0

**Comment by ruddell** [comment]
Social Login was removed from JHipster in v5, so it's no longer a part of this boilerplate.  Now it only supports social login for the OAuth option, [by following this documentation](https://www.jhipster.tech/tips/024_tip_enabling_social_login_with_oauth2.html).

You could use an old version of the boilerplate if you want, but I can't support bugs/issues in it as it has been a long time since JHipster v5 was released.  You can use an old version by adding it to the ignite command `ignite new OldApp -b jhipster@v1.10.2`
