### ISSUE TITLE
Customised React-navigation instead Of React-Native Navigation

### ISSUE THREAD

**Issue by arun1705** [ruddell/ignite-jhipster#88]
Is there any way to customised react-native navigation.I want to use react-navigation instead of react-native navigation.

**Comment by ruddell** [comment]
If you want to use `react-navigation` instead of `react-native-navigation`, you'll have to migrate the code manually. There's no way to generate with `react-navigation` at this point in time

If you do end up migrating, some sample code for the basic navigation would be appreciated. Then we can compare and validate if `react-navigation` has improved enough to be the default navigation.  When this boilerplate was originally released, `react-navigation` was very new and had performance issues for larger apps.
